### playbook.yml
---
- name: Init monitoring container
  hosts: monitoring
  become: true
  gather_facts: false
  remote_user: ubuntu
  tasks:
    - name: Clone repository
      command: git clone https://github.com/roninzp/zabbix-monitoring.git
    - name: Start zabbix
      command: cd zabbix-monitoring
      command: docker-compose -f ./docker-compose.yaml up -d


