### playbook.yml
---
- name: Init monitoring container
  hosts: monitoring
  become: true
  gather_facts: false
  remote_user: ubuntu
  tasks:
    - name: Copy monitoring start files
      copy:
        src: ../zabbix
        dest: /root
        force: yes
    - name: Start zabbix
      command: docker-compose -f ./docker-compose.yaml up -d
      args:
        chdir: /root/zabbix
    - name: Install ICMP Ping template
      copy:
        src: ../zabbix/templates/Template_Module_ICMP_Ping_3.4.0.xml
        dest: /root/zabbix/zbx_env/var/lib/zabbix/modules/
        force: yes


